name: Firefox tests

on:
  push
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 2,10,18 * * *'


jobs:
  cypress-e2e:
    name: Run on firefox
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.14.0-chrome-135.0.7049.84-1-ff-137.0.1-edge-135.0.3179.54-1
      options: --user 1001

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true


    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '14.18.0'


    - name: Install Cypress and reporters
      run: |
        npm install --save-dev cypress
        npm install cypress-multi-reporters --save-dev
        npm install mochawesome --save-dev
        $(npm bin)/cypress cache path
        $(npm bin)/cypress cache list
        $(npm bin)/cypress verify
        mkdir -p public/videos

    - name: Attempt to fix vulnerabilities (optional)
      run: npm audit fix || true

    - name: Set var 
      run: |
        echo "TOOL_TESTS=$(grep TOOL_TESTS cypress.config.js | sed 's/TOOL_TESTS//' | sed 's/"//g' |sed 's/,//' | sed 's/://')" | tr -d ' ' >> $GITHUB_ENV
        echo "REQUESTS_TESTS=$(grep REQUESTS_TESTS cypress.config.js | sed 's/REQUESTS_TESTS//' | sed 's/"//g' |sed 's/,//' | sed 's/://')" | tr -d ' ' >> $GITHUB_ENV 

    
    - name: Run firefox tool tests
      run: |
        touch toolTest.log
        toolTestsCommand='npx cypress run --browser firefox --spec ./cypress/e2e/toolTests.js \
        --config trashAssetsBeforeRuns=false'
        if eval $toolTestsCommand >> toolTest.log
        then
          cat toolTest.log
        else
          if grep -q 'Error: ffmpeg exited' toolTest.log \
          || grep -q 'Because this error occurred during a `before each` hook' toolTest.log \
          || grep -q 'EISDIR: illegal operation on a directory, read' toolTest.log;
          then
            cat toolTest.log; $toolTestsCommand
          else
            cat toolTest.log; exit 1
          fi
        fi 
      if: ${{env.TOOL_TESTS == 'true'}}

    - name: Copy test execution videos 
      run: |
        cp cypress/videos/* public/videos
      if: ${{ always() && (env.TOOL_TESTS == 'true')}}

    - name: Run firefox requests tests
      run: |
        touch requestsTest.log
        requestsTestsCommand='npx cypress run --browser firefox --spec ./cypress/e2e/requestsTests.js \
        --config trashAssetsBeforeRuns=false'
        if eval $requestsTestsCommand >> requestsTest.log
        then
          cat requestsTest.log
        else
          if grep -q 'Error: ffmpeg exited' requestsTest.log \
          || grep -q 'Because this error occurred during a `before each` hook' requestsTest.log \
          || grep -q 'EISDIR: illegal operation on a directory, read' requestsTest.log;
          then
            cat requestsTest.log; $requestsTestsCommand
          else
            cat requestsTest.log; exit 1
          fi
        fi 
      if: ${{always() && (env.REQUESTS_TESTS == 'true')}}


    - name: Copy test execution videos 
      run: |
        cp cypress/videos/* public/videos
      if: ${{ always() && (env.REQUESTS_TESTS == 'true') }}

    - name: Merge test results into one
      run: npx mochawesome-merge cypress/results/json/*.json > index.json
      if: ${{ always() && ((env.REQUESTS_TESTS == 'true') || (env.TOOL_TESTS == 'true')) }}

    - name: Generate HTML report
      run: npx marge index.json --reportDir public --assetsDir public/assets --reportPageTitle index.html
      if: ${{ always() && ((env.REQUESTS_TESTS == 'true') || (env.TOOL_TESTS == 'true')) }}

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      if: ${{ always() && ((env.REQUESTS_TESTS == 'true') || (env.TOOL_TESTS == 'true')) }}
